name: Team 14 Powell Puff Gang's approval workflow

on:
  push:

jobs:
  JSDoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build JSDoc
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./source/documentation
          template: minami

      - name: Convert output to markdown
        run: |
          cd ./source
          npm install --save-dev jsdoc-to-markdown
          npx jsdoc2md `find . -path ./node_modules -prune -o -name "*.js"` > ./documentation/JSDocumentation.md
          cd ..

      # - name: Deploy documentation to Github wiki
      #  uses: SwiftDocOrg/github-wiki-publish-action@v1
      #  with:
      #    # A path to the directory of files to publish
      #    path: "source/documentation"
      #  env:
      #    GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Commit documentation
        run: |
           git config --local user.email "nwong@ucsd.edu"
           git config --local user.name "nwong524"
           git add ./source/documentation
           git commit -m "Update Documentation" -a

      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} # The branch or tag ref that triggered the workflow run

  ESLint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ESlint on directory
        run: npx eslint ./source

  Tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Jest
        run: npm install --save-dev jest babel-jest @babel/core @babel/preset-env --prefix ./source

      - name: Install Puppeteer Container
        run: npm install --save-dev puppeteer jest-puppeteer --prefix ./source

      - name: Run Unit and E2E tests via Jest and Puppeteer
        run: npm run test --prefix ./source


  # Puppeteer-E2E:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  # Jest-Unit-Tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  # Cypress-E2E:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2