name: Team 14 Powell Puff Gang's approval workflow
# on: push
# jobs:
#    push-check:
#      runs-on: ubuntu-latest
#      steps:
#        - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
#        - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#        - name: Check out repository code
#          uses: actions/checkout@v2
#        - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
#        - run: echo "The workflow is now ready to test your code via Jest."
#        - run: echo "Checking JSDocs documentation ..."
#        - name: List files in the repository
#          run: |
#            ls ${{ github.workspace }}
#        - run: echo "Check CodeFactor.io for quality checks"
#        - run: echo "This job's status is ${{ job.status }}."
